num1=input('Enter the first Number : ')
num2=input('Enter the second Number : ')
add= int(num1)+int(num2)
print('Addition :', add)
sub= int(num1)-int(num2)
print('Subtraction :', sub)
mul= int(num1)*int(num2)
print('Multiplication :', mul)
div= int(num1)/int(num2)
print('Division :', div)